included_forms: "commerce_checkout_flow_cypress_multistep_default\r\nprofile_customer_edit_form\r\nprofile_customer_add_form\r\n/views_form_commerce_cart_form_default_\\d+/"
excluded_forms: ''
included_selectors: ''
excluded_selectors: ''
mark_required: 1
select_field_default_value: 1
