smtp_on: true
smtp_host: cypress-com.mail.protection.outlook.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: tls
smtp_username: ''
smtp_password: ''
smtp_from: cysupport@cypress.com
smtp_fromname: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
