<?php

/**
 * @file
 * Contains cypress_store_vendor.module.
 */

use Drupal\cypress_store_vendor\Vendor\Avnet;

/**
 * Implements hook_mail().
 */
function cypress_store_vendor_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'logger':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('logger: @title', array('@title' => $params['title']), $options);
      $message['body'][] = $params['message'];
      break;

    case 'shipping_confirmation_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@title', array('@title' => $params['title']), $options);
      $message['body'][] = $params['message'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}

/**
 * Implements hook_cron().
 *
 * Cron to update Avnet inventory details.
 */
function cypress_store_vendor_cron() {
  $avnet_handler = new Avnet();
  $avnet_handler->updateInventory();
}
