<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_combine_carts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_combine_carts module.
    case 'help.page.commerce_combine_carts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Combines multiple carts so that users only ever have one.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_user_login().
 */
function commerce_combine_carts_user_login(\Drupal\user\UserInterface $account) {
  /** @var \Drupal\commerce_combine_carts\CartUnifier $cart_unifier */
  $cart_unifier = \Drupal::service('commerce_combine_carts.cart_unifier');
  $cart_unifier->combineUserCarts($account);
}
